version: '2'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  schedule:
    build:
      context: ./schedule
      dockerfile: Docker-schedule


